# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mater_or_Client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QPoint
import Client
import Master
import Tutorial
import Master_or_Client_GUI




class master_or_client_Form(QtWidgets.QWidget, Master_or_Client_GUI.Ui_Form_master_or_client):
    def __init__(self, parent=None):
        super(master_or_client_Form, self).__init__(parent)
        self.setupUi(self)
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        #Center the window
        qr = self.frameGeometry()
        cp = QtWidgets.QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())
        
        self.setWindowTitle("ChainSpoT")
        self.setWindowIcon(QtGui.QIcon("Icons/logo.png"))
        self.oldPos = self.pos()
        self.setWindowFlag(Qt.FramelessWindowHint) #Hide the title bar of window
        self.pushButton_4.clicked.connect(self.master)
        self.pushButton_5.clicked.connect(self.client)
        self.pushButton_6.clicked.connect(self.tutorial)
        self.bn_close.clicked.connect(self.exit)
        self.bn_min.clicked.connect(self.showMinimized)
        
    def exit(self):
        self.close()

    def tutorial(self):
        self.w = Tutorial.tutorial_Form()
        self.w.show()
        self.close()  
              
    def client(self):
        self.w = Client.client_Form()
        self.w.show()
        self.close()

    def master(self):
        self.w = Master.master_Form()
        self.w.show()
        self.close()

    def mousePressEvent(self, event):
        self.oldPos = event.globalPos()

    def mouseMoveEvent(self, event):
        delta = QPoint (event.globalPos() - self.oldPos)
        self.move(self.x() + delta.x(), self.y() + delta.y())
        self.oldPos = event.globalPos()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    master_or_client = master_or_client_Form()
    master_or_client.show()
    sys.exit(app.exec_())