# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tutorial.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Icons_rc


class Ui_Form_tutorial(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1050, 765)
        Form.setStyleSheet("background-color: rgb(51,51,51);")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(50, 60, 241, 51))
        self.label_21.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:rgb(255,255,255);")
        self.label_21.setObjectName("label_21")
        self.lab_person = QtWidgets.QLabel(Form)
        self.lab_person.setGeometry(QtCore.QRect(870, 0, 55, 55))
        self.lab_person.setMaximumSize(QtCore.QSize(55, 55))
        self.lab_person.setText("")
        self.lab_person.setPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/peple.png"))
        self.lab_person.setScaledContents(False)
        self.lab_person.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_person.setObjectName("lab_person")
        self.bn_min = QtWidgets.QPushButton(Form)
        self.bn_min.setGeometry(QtCore.QRect(930, 0, 55, 55))
        self.bn_min.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_min.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/hideAsset 53.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_min.setIcon(icon)
        self.bn_min.setIconSize(QtCore.QSize(22, 22))
        self.bn_min.setFlat(True)
        self.bn_min.setObjectName("bn_min")
        self.bn_close = QtWidgets.QPushButton(Form)
        self.bn_close.setGeometry(QtCore.QRect(990, 0, 55, 55))
        self.bn_close.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/closeAsset 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_close.setIcon(icon1)
        self.bn_close.setIconSize(QtCore.QSize(22, 22))
        self.bn_close.setFlat(True)
        self.bn_close.setObjectName("bn_close")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 130, 951, 581))
        self.groupBox.setStyleSheet("background-color: rgb(91,90,90);\n"
"border:0px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(840, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 530, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"")
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(390, 20, 211, 51))
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(255,255,255);")
        self.label_22.setObjectName("label_22")
        self.lab_home_main_disc = QtWidgets.QLabel(self.groupBox)
        self.lab_home_main_disc.setGeometry(QtCore.QRect(10, 100, 487, 395))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lab_home_main_disc.setFont(font)
        self.lab_home_main_disc.setStyleSheet("color:rgb(255,255,255);")
        self.lab_home_main_disc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lab_home_main_disc.setWordWrap(True)
        self.lab_home_main_disc.setObjectName("lab_home_main_disc")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(490, 60, 461, 421))
        self.label.setStyleSheet("background-image: url(:/Icons/Block.png);")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(":/Icons/Block.png"))
        self.label.setScaledContents(True)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.pushButton_6.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.checkBox_2.raise_()
        self.lab_home_main_disc.raise_()
        self.label.raise_()
        self.label_22.raise_()
        self.lab_person_2 = QtWidgets.QLabel(Form)
        self.lab_person_2.setGeometry(QtCore.QRect(868, 0, 55, 55))
        self.lab_person_2.setMaximumSize(QtCore.QSize(55, 55))
        self.lab_person_2.setText("")
        self.lab_person_2.setPixmap(QtGui.QPixmap(":/Icons/people.png"))
        self.lab_person_2.setScaledContents(False)
        self.lab_person_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_person_2.setObjectName("lab_person_2")
        self.bn_min_2 = QtWidgets.QPushButton(Form)
        self.bn_min_2.setGeometry(QtCore.QRect(932, 0, 55, 55))
        self.bn_min_2.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_min_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_min_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_min_2.setIcon(icon2)
        self.bn_min_2.setIconSize(QtCore.QSize(22, 22))
        self.bn_min_2.setFlat(True)
        self.bn_min_2.setObjectName("bn_min_2")
        self.bn_close_2 = QtWidgets.QPushButton(Form)
        self.bn_close_2.setGeometry(QtCore.QRect(992, 0, 55, 55))
        self.bn_close_2.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_close_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_close_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_close_2.setIcon(icon3)
        self.bn_close_2.setIconSize(QtCore.QSize(22, 22))
        self.bn_close_2.setFlat(True)
        self.bn_close_2.setObjectName("bn_close_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_21.setText(_translate("Form", "ChainSpoT"))
        self.bn_min.setToolTip(_translate("Form", "Minimize"))
        self.bn_close.setToolTip(_translate("Form", "Close"))
        self.pushButton_6.setText(_translate("Form", "Skip"))
        self.pushButton_4.setText(_translate("Form", "Previous"))
        self.pushButton_5.setText(_translate("Form", "Next"))
        self.checkBox_2.setText(_translate("Form", "don\'t show me this again"))
        self.label_22.setText(_translate("Form", "Tutorial"))
        self.lab_home_main_disc.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.bn_min_2.setToolTip(_translate("Form", "Minimize"))
        self.bn_close_2.setToolTip(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_tutorial()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
